# Generated by Django 5.2.6 on 2025-09-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("blood_type", models.CharField(max_length=3)),
                ("age", models.IntegerField()),
                ("allergies", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.patient"
                    ),
                ),
            ],
        ),
    ]
