# Generated by Django 5.2.6 on 2025-09-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_doctor_patient_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalReports",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("Test_Name", models.CharField(default="N/A", max_length=100)),
                ("report_file", models.FileField(upload_to="medical_reports/")),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.patient"
                    ),
                ),
            ],
        ),
    ]
