# Generated by Django 5.2.6 on 2025-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_doctor_user_patient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
