# Generated by Django 5.2.6 on 2025-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0005_alter_patient_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreports",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalreports",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
