# Generated by Django 5.2.6 on 2025-09-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0006_medicalreports_extracted_text_medicalreports_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("medication_id", models.AutoField(primary_key=True, serialize=False)),
                ("medicine_name", models.CharField(max_length=100)),
                ("date_prescribed", models.DateTimeField(auto_now_add=True)),
                ("dosage", models.CharField(max_length=100)),
                ("instructions", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.patient"
                    ),
                ),
                (
                    "prescribed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.doctor",
                    ),
                ),
            ],
        ),
    ]
